"""recipient email and preferred courier

Revision ID: 9b80ea1fa66f
Revises: 9873f7487057
Create Date: 2026-08-18 09:55:11.360178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b80ea1fa66f'
down_revision = '9873f7487057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_courier_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('recipient_email', sa.String(length=180), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_orders_preferred_courier_id_users'), 'users', ['preferred_courier_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_orders_preferred_courier_id_users'), type_='foreignkey')
        batch_op.drop_column('recipient_email')
        batch_op.drop_column('preferred_courier_id')

    # ### end Alembic commands ###
